# Generated by Django 4.0.2 on 2022-03-09 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_referal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='strike_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
