# Generated by Django 4.0.2 on 2022-03-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_user_user_image_alter_book_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
