# Generated by Django 4.0.2 on 2022-03-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_book_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
