# Generated by Django 4.0.2 on 2022-04-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_book_book_file_userbooks_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=400),
        ),
    ]
