# Generated by Django 4.0.2 on 2022-04-05 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_chapter_chapter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
