# Generated by Django 4.0.2 on 2022-05-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_withdrawer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawer',
            name='owner',
            field=models.CharField(max_length=300),
        ),
    ]
